Added calculation of medians
paritytech/metrics pull request #17
Opened 2024-04-24 14:53 UTC by Bullrich

Added the ability to calculate the median, which is now also shown, before showing the averages.

Resolves #16

2024-04-24 14:54 UTC, Bullrich commented
Find an example of how the project work here: [8818637658](https://github.com/paritytech/metrics/actions/runs/8818637658)

2024-04-24 15:28 UTC, Bullrich commented
# Example output:

<details><summary>Polkadot-SDK metrics</summary>
<h1>Metrics for paritytech/polkadot-sdk</h1>
<h1>Pull Requests</h1>

```mermaid
  pie title Pull Requests for the repository
  "Open" : 273
  "Merged" : 1582
  "Closed" : 363
  ```
<h3>PR review median</h3>

```mermaid
    gantt
        title Average PR time (days)
        dateFormat  X
        axisFormat %s
        section To close
        17 : 0, 17
        section To first review
        10 : 0, 10
        section Reviews per PR
        5 : 0, 5
  ```
<h3>Median duration per month</h3>

```mermaid
gantt
  title Median time to first review (days)
  dateFormat X
  axisFormat %s
  section Aug 2023
    1 : 0, 1
    section Sep 2023
    2 : 0, 2
    section Oct 2023
    2 : 0, 2
    section Nov 2023
    24 : 0, 24
    section Dec 2023
    2 : 0, 2
    section Jan 2024
    28 : 0, 28
    section Feb 2024
    2 : 0, 2
    section Mar 2024
    22 : 0, 22
```
```mermaid
gantt
  title Median time to merge (days)
  dateFormat X
  axisFormat %s
  section Aug 2023
    2 : 0, 2
    section Sep 2023
    2 : 0, 2
    section Oct 2023
    27 : 0, 27
    section Nov 2023
    26 : 0, 26
    section Dec 2023
    22 : 0, 22
    section Jan 2024
    26 : 0, 26
    section Feb 2024
    25 : 0, 25
    section Mar 2024
    2 : 0, 2
```
```mermaid
gantt
  title Median reviews per PR per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    3 : 0, 3
    section Sep 2023
    21 : 0, 21
    section Oct 2023
    2 : 0, 2
    section Nov 2023
    2 : 0, 2
    section Dec 2023
    2 : 0, 2
    section Jan 2024
    3 : 0, 3
    section Feb 2024
    2 : 0, 2
    section Mar 2024
    2 : 0, 2
```
<h3>PR review average</h3>

```mermaid
    gantt
        title Average PR time (days)
        dateFormat  X
        axisFormat %s
        section To close
        16 : 0, 16
        section To first review
        10 : 0, 10
        section Reviews per PR
        7 : 0, 7
  ```
<h3>Average duration per month</h3>

```mermaid
gantt
  title Average time to first review (days)
  dateFormat X
  axisFormat %s
  section Aug 2023
    2 : 0, 2
    section Sep 2023
    6 : 0, 6
    section Oct 2023
    8 : 0, 8
    section Nov 2023
    9 : 0, 9
    section Dec 2023
    11 : 0, 11
    section Jan 2024
    21 : 0, 21
    section Feb 2024
    7 : 0, 7
    section Mar 2024
    14 : 0, 14
```
```mermaid
gantt
  title Average time to merge (days)
  dateFormat X
  axisFormat %s
  section Aug 2023
    3 : 0, 3
    section Sep 2023
    6 : 0, 6
    section Oct 2023
    14 : 0, 14
    section Nov 2023
    18 : 0, 18
    section Dec 2023
    20 : 0, 20
    section Jan 2024
    28 : 0, 28
    section Feb 2024
    16 : 0, 16
    section Mar 2024
    19 : 0, 19
```
```mermaid
gantt
  title Average reviews per PR per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    11 : 0, 11
    section Sep 2023
    8 : 0, 8
    section Oct 2023
    9 : 0, 9
    section Nov 2023
    7 : 0, 7
    section Dec 2023
    5 : 0, 5
    section Jan 2024
    5 : 0, 5
    section Feb 2024
    6 : 0, 6
    section Mar 2024
    5 : 0, 5
```
<h3>Metrics over time</h3>

```mermaid
gantt
  title New PRs per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    152 : 0, 152
    section Sep 2023
    292 : 0, 292
    section Oct 2023
    243 : 0, 243
    section Nov 2023
    321 : 0, 321
    section Dec 2023
    192 : 0, 192
    section Jan 2024
    237 : 0, 237
    section Feb 2024
    262 : 0, 262
    section Mar 2024
    261 : 0, 261
```
```mermaid
gantt
  title Merged PRs per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    17 : 0, 17
    section Sep 2023
    118 : 0, 118
    section Oct 2023
    99 : 0, 99
    section Nov 2023
    116 : 0, 116
    section Dec 2023
    94 : 0, 94
    section Jan 2024
    104 : 0, 104
    section Feb 2024
    115 : 0, 115
    section Mar 2024
    112 : 0, 112
```
```mermaid
gantt
  title Lines changed per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    24 : 0, 24
    section Sep 2023
    28 : 0, 28
    section Oct 2023
    22 : 0, 22
    section Nov 2023
    24 : 0, 24
    section Dec 2023
    228 : 0, 228
    section Jan 2024
    2 : 0, 2
    section Feb 2024
    26 : 0, 26
    section Mar 2024
    20 : 0, 20
```
```mermaid
gantt
  title Reviews per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    19 : 0, 19
    section Sep 2023
    551 : 0, 551
    section Oct 2023
    415 : 0, 415
    section Nov 2023
    394 : 0, 394
    section Dec 2023
    387 : 0, 387
    section Jan 2024
    945 : 0, 945
    section Feb 2024
    351 : 0, 351
    section Mar 2024
    640 : 0, 640
```
<h3>Top reviewers</h3>

```mermaid
  gantt
    title Top reviewer per month
    dateFormat X
    axisFormat %s
    section Aug 2023
    ggwpez : 0, 65
    section Sep 2023
    kianenigma : 0, 154
    section Oct 2023
    bkchr : 0, 148
    section Nov 2023
    bkchr : 0, 195
    section Dec 2023
    liamaharon : 0, 95
    section Jan 2024
    ggwpez : 0, 157
    section Feb 2024
    kianenigma : 0, 48
    section Mar 2024
    Ank4n : 0, 1
    section Apr 2024
    thiolliere : 0, 4
    section Feb 2024
    ggwpez : 0, 92
    section Mar 2024
    kianenigma : 0, 148
  ```
<h4>Reviewer of the month</h4>
<img src="https://avatars.githubusercontent.com/u/5588131?u=54683d39167504efa814928e52e04f76ed116f12&v=4" alt="kianenigma's avatar">
@kianenigma with 148 reviews!
<h3>Top reviewer</h3>

<img src="https://avatars.githubusercontent.com/u/10380170?u=6f8ecfaf656e435fa908d03f75e48fa28dc16b5d&v=4" alt="ggwpez's avatar">

@ggwpez with a **total of 1176 reviews**!<h1>Issues</h1>

```mermaid
  pie title Issues for the repository
  "Open" : 1303
  "Closed" : 620
  ```
<h3>Issue comment median</h3>

```mermaid
    gantt
        title Average activity time (days)
        dateFormat  X
        axisFormat %s
        section Time to close
        173 : 0, 173
        section Time to first comment
        27 : 0, 27
        section Average comments
        7 : 0, 7
  ```
<h3>Median duration per month</h3>

```mermaid
gantt
  title Median time to first comment (days)
  dateFormat X
  axisFormat %s
  section Mar 2018
    0 : 0, 0
    section Jan 2019
    0 : 0, 0
    section Feb 2019
    26 : 0, 26
    section Apr 2019
    1 : 0, 1
    section May 2019
    0 : 0, 0
    section Jun 2019
    0 : 0, 0
    section Jul 2019
    0 : 0, 0
    section Aug 2019
    26 : 0, 26
    section Sep 2019
    3 : 0, 3
    section Oct 2019
    0 : 0, 0
    section Jan 2020
    8 : 0, 8
    section Feb 2020
    164 : 0, 164
    section Mar 2020
    5 : 0, 5
    section Apr 2020
    16 : 0, 16
    section May 2020
    0 : 0, 0
    section Jun 2020
    0 : 0, 0
    section Jul 2020
    73 : 0, 73
    section Aug 2020
    26 : 0, 26
    section Sep 2020
    36 : 0, 36
    section Oct 2020
    5 : 0, 5
    section Nov 2020
    0 : 0, 0
    section Dec 2020
    14 : 0, 14
    section Jan 2021
    0 : 0, 0
    section Feb 2021
    6 : 0, 6
    section Mar 2021
    3 : 0, 3
    section Apr 2021
    80 : 0, 80
    section May 2021
    94 : 0, 94
    section Jun 2021
    6 : 0, 6
    section Jul 2021
    121 : 0, 121
    section Aug 2021
    0 : 0, 0
    section Sep 2021
    1 : 0, 1
    section Oct 2021
    8 : 0, 8
    section Nov 2021
    28 : 0, 28
    section Dec 2021
    4 : 0, 4
    section Jan 2022
    36 : 0, 36
    section Feb 2022
    3 : 0, 3
    section Mar 2022
    54 : 0, 54
    section Apr 2022
    24 : 0, 24
    section May 2022
    22 : 0, 22
    section Jun 2022
    67 : 0, 67
    section Jul 2022
    70 : 0, 70
    section Aug 2022
    7 : 0, 7
    section Sep 2022
    54 : 0, 54
    section Oct 2022
    77 : 0, 77
    section Nov 2022
    40 : 0, 40
    section Dec 2022
    29 : 0, 29
    section Jan 2023
    5 : 0, 5
    section Feb 2023
    7 : 0, 7
    section Mar 2023
    38 : 0, 38
    section Apr 2023
    24 : 0, 24
    section May 2023
    4 : 0, 4
    section Jun 2023
    31 : 0, 31
    section Jul 2023
    40 : 0, 40
    section Aug 202 [...]

2024-04-30 13:00 UTC, Bullrich commented
@mutantcornholio I combined the medians and averages into a single chart.

Let me know how it looks now:

<details><summary>Metrics for Polkadot-SDK</summary>

<h1>Metrics for paritytech/polkadot-sdk</h1>
<h1>Pull Requests</h1>

```mermaid
  pie title Pull Requests for the repository
  "Open" : 270
  "Merged" : 1614
  "Closed" : 373
  ```
<h3>PR review</h3>

```mermaid
    gantt
        title Average PR time (days)
        dateFormat  X
        axisFormat %s
        section To close
        Average 10 : 0, 10
        Median 2 : 0, 2
        section To first review
        Average 4 : 0, 4
        Median 0 : 0, 0
        section Reviews per PR
        Average 7 : 0, 7
        Median 3 : 0, 3
  ```
<h3>Duration per month</h3>

```mermaid
gantt
  title Time to first review (hours)
  dateFormat X
  axisFormat %s
  section Aug 2023
    Average 14 : 0, 14
    Median 4 : 0, 4
    section Sep 2023
    Average 77 : 0, 77
    Median 20 : 0, 20
    section Oct 2023
    Average 96 : 0, 96
    Median 17 : 0, 17
    section Nov 2023
    Average 72 : 0, 72
    Median 8 : 0, 8
    section Dec 2023
    Average 89 : 0, 89
    Median 10 : 0, 10
    section Jan 2024
    Average 171 : 0, 171
    Median 9 : 0, 9
    section Feb 2024
    Average 68 : 0, 68
    Median 12 : 0, 12
    section Mar 2024
    Average 120 : 0, 120
    Median 10 : 0, 10
```
```mermaid
gantt
  title Time to merge (hours)
  dateFormat X
  axisFormat %s
  section Aug 2023
    Average 27 : 0, 27
    Median 14 : 0, 14
    section Sep 2023
    Average 105 : 0, 105
    Median 48 : 0, 48
    section Oct 2023
    Average 227 : 0, 227
    Median 51 : 0, 51
    section Nov 2023
    Average 236 : 0, 236
    Median 26 : 0, 26
    section Dec 2023
    Average 302 : 0, 302
    Median 52 : 0, 52
    section Jan 2024
    Average 368 : 0, 368
    Median 27 : 0, 27
    section Feb 2024
    Average 270 : 0, 270
    Median 60 : 0, 60
    section Mar 2024
    Average 322 : 0, 322
    Median 62 : 0, 62
```
```mermaid
gantt
  title Reviews per PR per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    Average 11 : 0, 11
    Median 5 : 0, 5
    section Sep 2023
    Average 8 : 0, 8
    Median 3 : 0, 3
    section Oct 2023
    Average 9 : 0, 9
    Median 3 : 0, 3
    section Nov 2023
    Average 7 : 0, 7
    Median 3 : 0, 3
    section Dec 2023
    Average 5 : 0, 5
    Median 3 : 0, 3
    section Jan 2024
    Average 5 : 0, 5
    Median 3 : 0, 3
    section Feb 2024
    Average 6 : 0, 6
    Median 3 : 0, 3
    section Mar 2024
    Average 5 : 0, 5
    Median 3 : 0, 3
```
<h3>Metrics over time</h3>

```mermaid
gantt
  title New PRs per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    152 : 0, 152
    section Sep 2023
    292 : 0, 292
    section Oct 2023
    243 : 0, 243
    section Nov 2023
    321 : 0, 321
    section Dec 2023
    192 : 0, 192
    section Jan 2024
    237 : 0, 237
    section Feb 2024
    262 : 0, 262
    section Mar 2024
    261 : 0, 261
```
```mermaid
gantt
  title Merged PRs per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    59 : 0, 59
    section Sep 2023
    189 : 0, 189
    section Oct 2023
    158 : 0, 158
    section Nov 2023
    215 : 0, 215
    section Dec 2023
    157 : 0, 157
    section Jan 2024
    195 : 0, 195
    section Feb 2024
    173 : 0, 173
    section Mar 2024
    165 : 0, 165
```
```mermaid
gantt
  title Lines changed per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    Average 1132 : 0, 1132
    Median 52 : 0, 52
    section Sep 2023
    Average 597 : 0, 597
    Median 28 : 0, 28
    section Oct 2023
    Average 335 : 0, 335
    Median 33 : 0, 33
    section Nov 2023
    Average 583 : 0, 583
    Median 26 : 0, 26
    section Dec 2023
    Average 396 : 0, 396
    Median 20 : 0, 20
    section Jan 2024
    Average 432 : 0, 432
    Median 17 : 0, 17
    section Feb 2024
    Average 407 : 0, 407
    Median 39 : 0, 39
    section Mar 2024
    Average 410 : 0, 410
    Median 43 : 0, 43
```
```mermaid
gantt
  title Reviews per month
  dateFormat X
  axisFormat %s
  section Aug 2023
    834 : 0, 834
    section Sep 2023
    14831 : 0, 14831
    section Oct 2023
    10989 : 0, 10989
    section Nov 2023
    10620 : 0, 10620
    section Dec 2023
    10356 : 0, 10356
    section Jan 2024
    23790 : 0, 23790
    section Feb 2024
    9572 : 0, 9572
    section Mar 2024
    16358 : 0, 16358
```
<h3>Top reviewers</h3>

```mermaid
  gantt
    title Top reviewer per month
    dateFormat X
    axisFormat %s
    section Aug 2023
    ggwpez : 0, 65
    section Sep 2023
    ggwpez : 0, 50
    section Oct 2023
    muraca : 0, 8
    section Nov 2023
    lexnv : 0, 4
    section Feb 2024
    alindima : 0, 31
    section Mar 2024
    dmitry-markin : 0, 10
    section Apr 2024
    bkchr : 0, 27
    section Sep 2023
    kianenigma : 0, 120
    section Oct 2023
    bkchr : 0, 148
    section Nov 2023
    bkchr : 0, 195
    section Dec 2023
    liamaharon : 0, 95
    section Jan 2024
    ggwpez : 0, 157
    section Feb 2024
    bkchr : 0, 124
    section Mar 2024
    kianenigma : 0, 145
  ```
<h4>Reviewer of the month</h4>
<img src="https://avatars.githubusercontent.com/u/5588131?u=54683d39167504efa814928e52e04f76ed116f12&v=4" alt="kianenigma's avatar">

@kianenigma with 145 reviews!
<h3>Top reviewer</h3>

<img src="https://avatars.githubusercontent.com/u/10380170?u=6f8ecfaf656e435fa908d03f75e48fa28dc16b5d&v=4" alt="ggwpez's avatar">

@ggwpez with a **total of 1202 reviews**!<h1>Issues</h1>

```mermaid
  pie title Issues for the repository
  "Open" : 1311
  "Closed" : 636
  ```
<h3>Issue comment</h3>

```mermaid
    gantt
        title Average activity time (days)
        dateFormat  X
        axisFormat %s
        section Time to close
        Median 82 : 0, 82
        Average 170 : 0, 170
        section Time to first comment
        Median 4 : 0, 4
        Average 27 : 0, 27
        section Average comments
        Median 3 : 0, 3
        Average 5 : 0, 5
  ```
<h3>Duration per month</h3>

```mermaid
gantt
  title Time to first comment (days)
  dateFormat X
  axisFormat %s
  section Mar 2018
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jan 2019
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Feb 2019
    Average 26 : 0, 26
    Median 24 : 0, 24
    section Apr 2019
    Average 1 : 0, 1
    Median 1 : 0, 1
    section May 2019
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jun 2019
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jul 2019
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Aug 2019
    Average 26 : 0, 26
    Median 26 : 0, 26
    section Sep 2019
    Average 3 : 0, 3
    Median 3 : 0, 3
    section Oct 2019
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jan 2020
    Average 8 : 0, 8
    Median 8 : 0, 8
    section Feb 2020
    Average 164 : 0, 164
    Median 41 : 0, 41
    section Mar 2020
    Average 5 : 0, 5
    Median 0 : 0, 0
    section Apr 2020
    Average 16 : 0, 16
    Median 6 : 0, 6
    section May 2020
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jun 2020
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Jul 2020
    Average 73 : 0, 73
    Median 1 : 0, 1
    section Aug 2020
    Average 26 : 0, 26
    Median 5 : 0, 5
    section Sep 2020
    Average 36 : 0, 36
    Median 1 : 0, 1
    section Oct 2020
    Average 5 : 0, 5
    Median 0 : 0, 0
    section Nov 2020
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Dec 2020
    Average 14 : 0, 14
    Median 0 : 0, 0
    section Jan 2021
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Feb 2021
    Average 6 : 0, 6
    Median 1 : 0, 1
    section Mar 2021
    Average 3 : 0, 3
    Median 1 : 0, 1
    section Apr 2021
    Average 80 : 0, 80
    Median 15 : 0, 15
    section May 2021
    Average 94 : 0, 94
    Median 3 : 0, 3
    section Jun 2021
    Average 6 : 0, 6
    Median 0 : 0, 0
    section Jul 2021
    Average 121 : 0, 121
    Median 93 : 0, 93
    section Aug 2021
    Average 0 : 0, 0
    Median 0 : 0, 0
    section Sep 2021
    Average [...]

2024-04-30 14:20 UTC, mutantcornholio requested changes

2024-04-30 14:20 UTC, mutantcornholio commented on src/reporter.ts
>    );
Double-aggregation introduces a lot of error! It almost never makes sense to do it.  
If you want want an average, or a median value for the whole period, calculate it directly, for all PRs/issues.

2024-05-02 07:24 UTC, mutantcornholio approved these changes

2024-05-02 07:56 UTC, merged